### PR TITLE
WANT TO BE ADDED TO THE LIST OF EXCHANGES

### PR DESCRIPTION
**Pull request by katherinefang**
To whom it may concern:
  This is Katherine, international marketing manager of KK Exchange(www.kkex.com). Here I will explain why I write. 

 [KKEX], a brand-new international blockchain asset exchange, is wholly owned by KKEX Technology Co., Ltd in the Republic of Seychelles. We are highly optimistic about the prospects for the development of BTG, and we have launched BTG/BTC trading pairs in our exchange.
 We hope that we can be one of your exchange rankings. If that could be possible, what we need to do or do you have time to talk about details?
  Your attention and answer will be fully appreciated. 
Best regards.

### CODE REVIEW

**Comment by StarbuckBG** [comment]
Hello Katherine. This is not the way to ask whatever in our network. GitHub is only for development work. You can contact us on Slack/Twitter, but making a pull request here is not ok (:

**Comment by katherinefang** [comment]
Hello, 
  Oh, I'm so sorry for this, I thought it works like others, they asked me to pull request there. 
  I have tried to contact your team by email, Slack, Twitter, but nobody responds. Could you help to tell me whom I can contact with? 
  Thanks for your response and sorry for my disturb. 
 Best regards. 
Katherine
 
 
------------------ Original ------------------

**Comment by StarbuckBG** [comment]
Contact me - Martin Kuvandzhiev

**Comment by StarbuckBG** [comment]
On Slack I mean.

**Pull request closed without merging**
