### PR TITLE
[WIP] Merge Bitcoin Core release tag "v0.15.1"

### PR DESCRIPTION
**Pull request by akx20000a**
This is the PR that merges Bitcoin Core 0.15.1 to BTG repo. For more information, please refer https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.15.1.md

ps) I didn't do anything about tuning commits for Bitcoin Gold. So, I recommend to review and make some additional commits for real use.

### CODE REVIEW

**Comment by akx20000a** [comment]
WIP
<pre><code>
user@user-VirtualBox:~/test/BTCGPU$ test/functional/test_runner.py
Temporary test directory at /tmp/bitcoin_test_runner_20180120_030314
/home/user/test/BTCGPU/src/bgoldd: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/user/test/BTCGPU/test/functional/create_cache.py", line 27, in <module>
    CreateCache().main()
  File "/home/user/test/BTCGPU/test/functional/test_framework/test_framework.py", line 143, in main
    self.stop_nodes()
  File "/home/user/test/BTCGPU/test/functional/test_framework/test_framework.py", line 273, in stop_nodes
    node.stop_node()
  File "/home/user/test/BTCGPU/test/functional/test_framework/test_node.py", line 119, in stop_node
    self.stop()
  File "/home/user/test/BTCGPU/test/functional/test_framework/test_node.py", line 68, in __getattr__
    assert self.rpc_connected and self.rpc is not None, "Error: no RPC connection"
AssertionError: Error: no RPC connection
Traceback (most recent call last):
  File "test/functional/test_runner.py", line 532, in <module>
    main()
  File "test/functional/test_runner.py", line 270, in main
    run_tests(test_list, config["environment"]["SRCDIR"], config["environment"]["BUILDDIR"], config["environment"]["EXEEXT"], tmpdir, args.jobs, args.coverage, passon_args)
  File "test/functional/test_runner.py", line 304, in run_tests
    subprocess.check_output([tests_dir + 'create_cache.py'] + flags + ["--tmpdir=%s/cache" % tmpdir])
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/home/user/test/BTCGPU/test/functional/create_cache.py', '--srcdir=/home/user/test/BTCGPU/src', '--configfile=/home/user/test/BTCGPU/test/functional/../config.ini', '--cachedir=/home/user/test/BTCGPU/test/cache', '--tmpdir=/tmp/bitcoin_test_runner_20180120_030314/cache']' returned non-zero exit status 1
</code></pre>

**Comment by akx20000a** [comment]
WIP
<pre><code>
zmq_test.py skipped
Traceback (most recent call last):
  File "test/functional/test_runner.py", line 532, in <module>
    main()
  File "test/functional/test_runner.py", line 270, in main
    run_tests(test_list, config["environment"]["SRCDIR"], config["environment"]["BUILDDIR"], config["environment"]["EXEEXT"], tmpdir, args.jobs, args.coverage, passon_args)
  File "test/functional/test_runner.py", line 314, in run_tests
    test_result, stdout, stderr = job_queue.get_next()
  File "test/functional/test_runner.py", line 395, in get_next
    stderr=log_stderr),
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
user@user-VirtualBox:~/test/BTCGPU$
</code></pre>

**Comment by h4x3rotab** [comment]
EPIC PR! Waiting for all the tests getting passed and will review it asap.

**Comment by akx20000a** [comment]
@h4x3rotab Done for now, needs review.

**Comment by akx20000a** [comment]
Will create an rebase hold on

**Comment by akx20000a** [comment]
Opened a new pr here https://github.com/BTCGPU/BTCGPU/pull/293

**Pull request closed without merging**
