### PR TITLE
Merge branch 0.15.1-bitcore into bitcore

### PR DESCRIPTION
**Pull request by akx20000a**
### PR specification

+ Merge 0.15.1-bitcore from https://github.com/satoshilabs/bitcoin-gold
+ Fix tests according to wilsonmeier/BTCGPU@9fb670d
+ Set '-dbmaxfilesize' optional
+ Now ./build.sh will produce bitcoin-gold-* instead of bgold-*

### New features from bitcore

New RPC Calls

- getblockdeltas
- getblockhashes
- getaddressmempool
- getaddressutxos
- getaddressdeltas
- getaddressbalance
- getaddresstxids
- getspentinfo

New daemon/wallet configuration

- addressindex
- spentindex
- timestampindex
- dbmaxopenfiles
- dbcompression
- dbmaxfilesize

### Test

+ Tested with ./test_bitcoin & ./test_runner.py
+ Live version deployed at https://btg.chainkorea.kr

### CODE REVIEW

**Comment by akx20000a** [comment]
Similar PR created on https://github.com/satoshilabs/bitcoin-gold/pull/1

**Comment by akx20000a** [comment]
Test result https://travis-ci.org/akx20000a/bitcoin-gold/builds/332794546

**Comment by akx20000a** [comment]
LOL git is unfriendly at python executables :D

**Comment by akx20000a** [comment]
Done

**Comment by h4x3rotab** [comment]
I’m reviewing wilson’s branch. We have been working on this for a while. So I will merge his branch first.

**Comment by akx20000a** [comment]
@h4x3rotab  It will be a sort-of duplicate pr :D

**Comment by h4x3rotab** [comment]
Yes. So you probably need to rebase later. I think it shouldn’t be hard.

**Comment by akx20000a** [comment]
@h4x3rotab  Ok 👍

**Comment by h4x3rotab** [comment]
Wilson has closed his PR. So I'm going to merge this. Would you like to rebase to bitcore branch? It will make it much easier to review the changes.

**Comment by akx20000a** [comment]
@h4x3rotab Which part do I need to rebase?

**Comment by akx20000a** [comment]
And these two commits db7b378, 287d089 are from satoshilabs, they must worked from the release tag v0.15.0.1 I think.

**Comment by akx20000a** [comment]
@h4x3rotab 
<pre><code>
user@user-VirtualBox:~/rebase/BTCGPU$ git fetch upstream
https://github.com/BTCGPU/BTCGPU URL에서
 * [새로운 브랜치]   0.15       -> upstream/0.15
 * [새로운 브랜치]   bitcore    -> upstream/bitcore
 * [새로운 브랜치]   master     -> upstream/master
 * [새로운 브랜치]   testnet1   -> upstream/testnet1
 * [새로운 브랜치]   testnet2   -> upstream/testnet2
user@user-VirtualBox:~/rebase/BTCGPU$ git merge upstream/bitcore
Already up-to-date.
</code></pre>

I think it is already done :D.

**Comment by akx20000a** [comment]
@h4x3rotab Forgot it, Thanks for telling me!

**Comment by h4x3rotab** [comment]
lgtm!

**Pull request merged**
