### PR TITLE
Prepare for Equihash<144,5> PoW upgrade

### PR DESCRIPTION
**Pull request by h4x3rotab**
Co-authored-by: h4x3rotab <h4x@bitcoingold.org>
Co-authored-by: jc <jc@jc>
Co-authored-by: Simon <simon@bitcartel.com>

### CODE REVIEW

**Comment by h4x3rotab** [comment]
Ref:
https://github.com/zcash/zcash/issues/1211#issuecomment-379882647
https://github.com/BTCPrivate/BitcoinPrivate/pull/181/commits/ee206ad9b07f46372a88b88bd59736c92612fe49

**Comment by h4x3rotab** [comment]
Difficulty change is still needed otherwise nobody can mine the first a few blocks.

**Comment by qasimsaleem1** [comment]
We are really looking forward for network upgrade.
Be fast upgrade the network

**Comment by h4x3rotab** [comment]
Rebased. Waiting for the pool & miner to test.

**Comment by akx20000a** [comment]
@h4x3rotab Is this compatible with any other equihash miner like Claymore?

**Comment by h4x3rotab** [comment]
@akx20000a I don't think so. The miner need to support 144,5.

**Comment by bonopord** [comment]
Шахтер нужно поддерживать 144,5.

2018-05-27 7:32 GMT+03:00 h4x3rotab <notifications@github.com>:

**Comment by qasimsaleem1** [comment]
Which miners does support 144,5 Does all gpu miner support 144,5? 
If all miner does not support and only some specific rig ??

**Comment by StarbuckBG** [comment]
We will ensure that there are available miners when the upgraded network starts. We are working in-house for modifying the nheqminer to support Equihash144.

**Comment by qasimsaleem1** [comment]
It is great for bitcoingold https://forum.bitcoingold.org/t/bitcoingold-upgrade-suggestions/1454
Hope so you will discuss

**Comment by h4x3rotab** [comment]
Manual test has been passed. Going to merge the change.

**Pull request merged**
