### PR TITLE
Add instruction of installing libsodium on Ubuntu 16.04.3

### PR DESCRIPTION
**Pull request by tnkmt**

### CODE REVIEW

**Comment by akx20000a** [comment]
If we had a ppa for libsodium-1.0.15....

**Comment by tnkmt** [comment]
After I tested it - it does not work

    bitcoin-qt: crypto/common.h:138: int init_and_check_sodium(): Assertion `crypto_sign_verify_detached(sig, message, sizeof(message), pk) != 0' failed.


Maybe it's better to build dependencies from 'depends' folder:

    $ cd depends
    $ make

I am trying it now.

**Comment by tnkmt** [comment]
It works with the dependencies from the `depends` directory.

**Comment by h4x3rotab** [comment]
lgtm. Thank you!

**Pull request merged**
