### PR TITLE
Bumped the version

### PR DESCRIPTION
**Pull request by TheSorrow1**

### CODE REVIEW

**Comment by akx20000a** [comment]
We need to edit those either 👍 
copyright
copyright2

**Comment by akx20000a** [comment]
I think you can find those on https://github.com/BTCGPU/BTCGPU/blob/master/src/init.cpp

**Comment by h4x3rotab** [comment]
What’s wrong with the startup page?

**Comment by akx20000a** [comment]
@h4x3rotab It shows that we have contributed since 2009

**Pull request merged**
