### PR TITLE
[WIP] Change name to Bitcoin Gold

### PR DESCRIPTION
**Pull request by TheSorrow1**
For the most part Misc, changing name.

### CODE REVIEW

**Comment by h4x3rotab** [comment]
Successfully compiled on Mac. Changed:
1. Client user agent string
2. Build rule name
3. macOS dot app file name

**Comment by h4x3rotab** [comment]
Modified the PR name to "[WIP] Change name to Bitcoin Gold". What hasn't been changed so far:

- Client name in qt-GUI
- Debian package name
- Documentations

Affected file
- configure.ac
- bitcoind.conf
- bitcoin.openrc
- Manual files in doc/man
- share/setup.nsi
- src/config/bitcoin-config.h

**Comment by h4x3rotab** [comment]
Will close the PR and reopen it for triggering Travis-CI

**Comment by h4x3rotab** [comment]
Would you like to continue on the following files?

- configure.ac
- bitcoin.openrc
- share/setup.nsi
- src/config/bitcoin-config.h

**Comment by 61ue5peed** [comment]
Looks good lets merge.

**Comment by h4x3rotab** [comment]
OK. All tests passed. Let's merge this and continue the renaming work with another PR.

**Pull request merged**
